language: c++
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/Marzogh/Travis-CI/master/install.sh)
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change
